name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 자동 실행
  workflow_dispatch:      # 수동 실행도 가능하게 설정

jobs:
  update-readme:
    name: Update Waka Stats
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.G_
